payload:
  controller:
    type: string
    default_value: "sim"
    description: "Controller type"
    validation:
      one_of<>: [["SimController", "GPIOController"]]
  
  sim:
    world_name:
      type: string 
      default_value: "sae"
      description: "Simulation World name"