#TODO: can differentiate between general (shared), gpio only, and sim only params
#TODO: Add necessary clamp param values (Ex. linear and angular velocity)
/**:
  ros__parameters:
    controller: "GPIOController" #Name of the controller plugin to instantiate. 
                      #Currently only have SimController or GPIOController
      
      #A/B pins will get mapped to LEFT/RIGHT
    pins:
      APHASE:  16
      AENABLE: 13
      BPHASE:  15
      BENABLE: 18

      ENCA_CH1: 0
      ENCA_CH2: 11
      ENCB_CH1: 9
      ENCB_CH2: 10
      SERVO:    14
    
    motor:
      pwm_frequency: 500.0 #Hz
      max_norm_speed: 1.0  #Must be between [0.0, 1.0]

    sim:
      world_name: "custom"