#TODO: can differentiate between general (shared), gpio only, and sim only params
#TODO: Add necessary clamp param values (Ex. linear and angular velocity)
/**:
  ros__parameters:
    controller: "SimController" #Name of the controller plugin to instantiate. 
                      #Currently only have SimController or GPIOController
    sim:
      world_name: "custom"